# Álgebra lineal numérica

## Conceptos básicos

**¿Qué es una matriz?**

$$
\begin{bmatrix} 
a_{1,1} & a_{1,2} & a_{1,3}& \ldots & a_{1,n}\\
a_{2,1} & a_{2,2} & a_{2,3}& \ldots & a_{2,n}\\
a_{3,1} & a_{3,2} & a_{3,3}& \ldots & a_{3,n}\\
\vdots  & \vdots  & \vdots &        & \vdots \\
a_{m,1} & a_{m,2} & a_{m,3}& \ldots & a_{m,n}\\
\end{bmatrix}
$$

Una matriz es un conjunto de elementos ordenados en filas y columnas. Donde los elementos $a_{i,j}$ pueden ser reales, complejos o funciones.

_Para facilitar la lectura de las expresiones de cálculo matricial, acordaremos la siguiente convención de notación:_

+ $\alpha,\,\beta,\,\gamma,\ldots,\omega$ para escalares
+ $\boldsymbol{a},\,\boldsymbol{b},\,\boldsymbol{c},\ldots,\boldsymbol{z}$ para vectores columna (vectores)
+ $\boldsymbol{a^{\prime}},\,\boldsymbol{b^{\prime}},\,\boldsymbol{c^{\prime}},\ldots,\boldsymbol{z^{\prime}}$ para vectores fila (co-vectores)
+ $A,\,B,\,C,\ldots,Z$ para matrices

### Suma de matrices

Para sumar dos matrices $A$ y $B$ deben ser de las mismas dimensiones. La suma se realiza elemento a elemento:

$$\begin{eqnarray*}
A_{m,n} + B_{m,n} &=& C_{m,n}\\
\begin{bmatrix} 
a_{1,1} & a_{1,2} & \ldots & a_{1,n}\\
a_{2,1} & a_{2,2} & \ldots & a_{2,n}\\
\vdots  & \vdots  &        & \vdots \\
a_{m,1} & a_{m,2} & \ldots & a_{m,n}\\
\end{bmatrix} + \begin{bmatrix} 
b_{1,1} & b_{1,2} & \ldots & b_{1,n}\\
b_{2,1} & b_{2,2} & \ldots & b_{2,n}\\
\vdots  & \vdots  &        & \vdots \\
b_{m,1} & b_{m,2} & \ldots & b_{m,n}\\
\end{bmatrix} &=& \begin{bmatrix} 
a_{1,1}+b_{1,1} & a_{1,2}+b_{1,2} & \ldots & a_{1,n}+b_{1,n}\\
a_{2,1}+b_{2,1} & a_{2,2}+b_{2,2} & \ldots & a_{2,n}+b_{2,n}\\
\vdots  & \vdots  &        & \vdots \\
a_{m,1}+b_{m,1} & a_{m,2}+b_{m,2} & \ldots & a_{m,n}+b_{m,n}\\
\end{bmatrix} \\
&=&  \begin{bmatrix} 
c_{1,1} & c_{1,2} & \ldots & c_{1,n}\\
c_{2,1} & c_{2,2} & \ldots & c_{2,n}\\
\vdots  & \vdots  &        & \vdots \\
c_{m,1} & c_{m,2} & \ldots & c_{m,n}\\
\end{bmatrix}\\
\begin{bmatrix}a_{i,j}\end{bmatrix}+\begin{bmatrix}b_{i,j}\end{bmatrix} &=&\begin{bmatrix}a_{i,j}+b_{i,j}\end{bmatrix} = \begin{bmatrix}c_{i,j}\end{bmatrix}
\end{eqnarray*}$$

### Producto de matrices por un escalar

El producto de un número real $\alpha$ y una matriz $A$ se denota por $\alpha A$, y se realiza multiplicando los elementos de $A$ por $\alpha$:

$$\begin{eqnarray*}
\alpha A &=& \begin{bmatrix} 
a_{1,1} & a_{1,2} & \ldots & a_{1,n}\\
a_{2,1} & a_{2,2} & \ldots & a_{2,n}\\
\vdots  & \vdots  &        & \vdots \\
a_{m,1} & a_{m,2} & \ldots & a_{m,n}\\
\end{bmatrix}\\
&=& \begin{bmatrix} 
\alpha\, a_{1,1} & \alpha\, a_{1,2} & \ldots & \alpha\, a_{1,n}\\
\alpha\, a_{2,1} & \alpha\, a_{2,2} & \ldots & \alpha\, a_{2,n}\\
\vdots  & \vdots  &        & \vdots \\
\alpha\, a_{m,1} & \alpha\, a_{m,2} & \ldots & \alpha\, a_{m,n}\\
\end{bmatrix}\\
\alpha\,\begin{bmatrix}a_{i,j}\end{bmatrix} &=& \begin{bmatrix}\alpha\,a_{i,j}\end{bmatrix}
\end{eqnarray*}$$

### Multiplicación de matrices

Para que la multiplicación de dos matrices $A$ y $B$ se pueda llevar a cabo, estas deben ser conformables, es decir, $A$ tiene el mismo número de columnas que $B$ tiene de filas:

$$\begin{eqnarray*}
A_{m,n}\,B_{n,p} &=& C_{m,p}\\
\begin{bmatrix} 
a_{1,1} & a_{1,2} & \ldots & a_{1,n}\\
a_{2,1} & a_{2,2} & \ldots & a_{2,n}\\
\vdots  & \vdots  &        & \vdots \\
a_{m,1} & a_{m,2} & \ldots & a_{m,n}\\
\end{bmatrix}\, \begin{bmatrix} 
b_{1,1} & b_{1,2} & \ldots & b_{1,n}\\
b_{2,1} & b_{2,2} & \ldots & b_{2,n}\\
\vdots  & \vdots  &        & \vdots \\
b_{m,1} & b_{m,2} & \ldots & b_{m,n}\\
\end{bmatrix} &=& \begin{bmatrix} 
c_{1,1} & c_{1,2} & \ldots & c_{1,p}\\
c_{2,1} & c_{2,2} & \ldots & c_{2,p}\\
\vdots  & \vdots  &        & \vdots \\
c_{m,1} & c_{m,2} & \ldots & c_{m,p}\\
\end{bmatrix}
\end{eqnarray*}$$

donde:

$$\begin{eqnarray*}
c_{i,j} &=&a_{i,1}\,b_{1,j}+ a_{i,2}\,b_{2,j}+\ldots+a_{i,n}\,b_{n,j}\\
c_{i,j} &=& \sum_{k=1}^{n}{a_{i,k}\,b_{k,j}}\, \text{para}\, i = 1,2,\ldots,m\, \text{y}\, j = 1,2,\ldots,p
\end{eqnarray*}$$



## Solución de sistemas de ecuaciones lineales

Si recordamos, en el **Paso 2** del algoritmo de Newton Raphson para sistemas de ecuaciones _no lineales_,  se tiene que resolver un sistema de ecuacioes lineales que se construye a partir de las funciones y del jacobiano de las funciones no lineales. Muchos de los problemas en ingniería se reducen a resolver un sistema de ecuaciones lineales.

Un sistema de $m$ ecuaciones lineales en $n$ incoógnitas tiene la forma:

$$\begin{matrix}
a_{1,1}x_1 & + & a_{1,2}x_2 & + & \ldots & + & a_{1,n}x_n & = & b_1\\
a_{2,1}x_1 & + & a_{2,2}x_2 & + & \ldots & + & a_{1,n}x_n & = & b_1\\
\vdots &   &       \vdots   & + &        &   & \vdots               \\
a_{m,1}x_1 & + & a_{m,2}x_2 & + & \ldots & + & a_{m,n}x_n & = & b_m\\
\end{matrix}$$

en notación matricial:

$$\begin{align*}
\begin{bmatrix}
a_{1,1} &  a_{1,2} &  \ldots &  a_{1,n}  \\
a_{2,1} &  a_{2,2} &  \ldots &  a_{1,n}  \\
\vdots  &  \vdots  &         &  \vdots   \\
a_{m,1} &  a_{m,2} &  \ldots &  a_{m,n} \\
\end{bmatrix}\, \begin{bmatrix}
x_1\\
x_2\\
\vdots\\
x_m
\end{bmatrix} &= \begin{bmatrix}
b_1\\
b_2\\
\vdots\\
b_m
\end{bmatrix}\\
A\,\boldsymbol{x}&=\boldsymbol{b}
\end{align*}$$

### Matriz aumentada $B$

Se forma con los elementos de la matriz de coefientes $A$ y los del vector $\boldsymbol{b}$.

$$
B = \left[
\begin{array}{cccc|c}
a_{1,1} & a_{1,2} & \ldots & a_{1,n} & b_{1}\\
a_{2,1} & a_{2,2} & \ldots & a_{2,n} & b_{2}\\
\vdots  & \vdots  &        & \vdots  & \vdots\\
a_{m,1} & a_{m,2}0 & \ldots & a_{m,n} & b_{m}\\
\end{array}
\right] = \left[\begin{array}{c|c}A&\boldsymbol{b}\end{array} \right]
$$

+ Si $\boldsymbol{b}=\boldsymbol{0}$ es un _sistema homogéneo_
+ si $\boldsymbol{b}\neq \boldsymbol{0}$ es un _sistema no homogéneo_ 
+ Si el rango de $A$ es igual al rango de $B$, el sistema es _consistente_
> + Un sistema consistente puede tener una solución o un número infinito de soluciones.
>> + Si $Rango\,A = n$, donde $n$ es el número de incógnitas, la solución es única.
>> + Si $Rango\,A < n$, hay un número infinito de soluciones.
+ Si el rango de $A$ es diferente al rango de $B$, el sistema es _inconsistente_
> + Un sistema inconsistente **no tiene solución**.

**Rango:** es el número de columnas o filas que son linealmente independientes. El rango fila y el rango columna siempre son iguales.

**Independencia lineal:** dado un conjunto de vectores $\boldsymbol{v_1},\, \boldsymbol{v_2},\,\ldots,\boldsymbol{v_n}$ se dice que son _linealmente independientes_ si :

$$a_1\boldsymbol{v_1} + a_2\boldsymbol{v_2} + \ldots + a_n\boldsymbol{v_n} = \boldsymbol{0} $$

se satiface únicamente cuando $a_1,\, a_2,\,\ldots,a_n $ son todos cero. De lo contrario, se dice qee son linealmente dependientes.


Python permite calcular el rango de una matriz, para ello, es necesario cargar la bilbioteca numpy,
para poder utilizar los método (o funciones) array y rank. Sea el sistema:


$$\begin{matrix}
2\, x_1 & + & 4\,x_2 &  = & 6\\
3\, x_1 & + & 6\,x_2 &  = & 5\\
\end{matrix}$$

Calcular el rango de $A$ y de $B$


In [1]:
import numpy as np    # Carga la biblioteca numpy 
A = np.array([[2, 4],[3,6]])    # Con array se crea la matriz A
B = np.array([[2,4,6],[3,6,5]])    # Se crea la matriz B

In [2]:
type(A)    # Verificamos el tipo de dato que es A

numpy.ndarray

In [3]:
# Para calcular el rango, se utiliza la operación rank 
rango_A = np.linalg.matrix_rank(A)    
rango_B = np.linalg.matrix_rank(B)

In [4]:
# El sistema es inconsiste porque el rango de A es diferente al rango de B
rango_A == rango_B

False

Si el sistema fuera homogéneo:
$$\begin{matrix}
2\, x_1 & + & 4\,x_2 &  = & 0\\
3\, x_1 & + & 6\,x_2 &  = & 0\\
\end{matrix}$$



In [5]:
A = np.array([[2, 4],[3,6]])
B = np.array([[2,4],[3,6]])

rango_A = np.linalg.matrix_rank(A)    
rango_B = np.linalg.matrix_rank(B)

rango_A == rango_B

True

Como se puede ver, si el sistema fuera homogéneo, el rango de A es igual al rango de B; de hecho un sistema homogéneo siempre es consistente. 

In [6]:
"""
Para determinar el número de ingógnitas del sistema, se llama al atributo shape 
sobre la matriz A:
"""
m,n = A.shape

In [7]:
# El número de filas es igual al número de ecuaciones
print m

2


In [8]:
# El número de columnas es igual al número de ingógnitas
print n

2


In [9]:
if rango_A == n:
    print "Solucion unica"
    

In [10]:
if rango_A < n:
    print "multiples soluciones"
    

multiples soluciones


### Operaciones elementales

+ Cambiar entre sí dos filas, o en su caso columnas.
+ Multiplicar una fila(columna) por un número real distinto de cero.
+ Sumar a una fila(columna) otra fila(columna) multiplicada por un número real.


### Métodos directos de solución

+ Eliminación Gaussiana

Sea el sistema: 

$$\begin{matrix}
a_{1,1}\, x_1 & + & a_{1,2}\,x_2 & + & a_{1,3}\,x_3 & = & b_1\\
a_{2,1}\, x_1 & + & a_{2,2}\,x_2 & + & a_{2,3}\,x_3 & = & b_2\\
a_{3,1}\, x_1 & + & a_{3,2}\,x_2 & + & a_{3,3}\,x_3 & = & b_3\\
\end{matrix}$$

Se realizan las operaciones elementales de multiplicación y suma hasta llegar a la _triangulización_ del sistema (triangular superior):

$$\begin{matrix}
a_{1,1}\, x_1 & + & a_{1,2}\,x_2 & + & a_{1,3}\,x_3 & = & b_1\\
              &   & a_{2,2}^{\prime\prime}\,x_2 & + & a_{2,3}^{\prime\prime}\,x_3 & = & b_2^{\prime\prime}\\
              &   &                       &   & a_{3,3}^{\prime\prime}\,x_3 & = & b_3^{\prime\prime}\\
\end{matrix}$$

Para resolver el sistema triangulizado, se aplica _sustitución regresiva_.

Una vez triangulizado el sistema, se puede calcular el _determinante_ de la matriz $A$ del sistema original.

$$\text{det} A = \prod_{i=1}^{n}{a_{i,i}}= a_{1,1}\,a_{2,2}\ldots a_{n,n}$$

+ Eliminación Gauss con pivoteo parcial

Se selecciona como pivote el coeficiente de máximo valor absoluto en la columna relevante de la matriz. Se toman las columnas como en el método gaussiano, de modo que se vayan eliminando las incógnitas $(x_1,\,x_2,\ldots,x_n)$ en orden natural.

+ Eliminación Gauss-Jordan

Este método continúa el proceso de triangulización, desde triangular superior hasta obtener una matriz diagonal, y por tanto, no se requiere la sustitución regresiva.

> + Inversa de una matriz por Gauss-Jordan

>> + La inversa $(A^{-1})$ de una matriz $(A)$, es aquella aquella que al multiplicarla por la matriz original $(A)$, el resultado es la matriz identidad $(I)$.

$$A\,A^{-1}=A^{-1}\,A=I$$

>> + Para que exista la inversa de una matriz, su determinante debe ser distinto de cero.

$$\text{det}A \neq 0$$

>> + Para calcular la inversa, en una misma matriz se coloca en la parte izquierda la matriz $A$, y en la parte derecha la identidad $I$:

$$\left[A|I\right]$$

>>> Se aplica el método de Gauss-Jordan hasta conseguir que en la parte izquierda quede la matriz identidad $(I)$, la matriz resulante en la parte derecha, será la matriz inversa $(A^{-1})$:

$$\left[A|I\right]\xrightarrow{Gauss-Jordan}\left[I|A^{-1}\right]$$

La biblioteca _Numpy_ posee el paquete _linalg_, el cual contiene métodos que permiten resolver sistemas de ecuaciones lineales, calcular el determinante y la inversa de una matriz:

+ **solve:** resuelve sistemas de ecuaciones lienales (consistente) de la forma $A\,\boldsymbol{x}=\boldsymbol{b}$

+ **inv:** permite calcular la inversa de una matriz

+ **det:** calcula el determinante de una matriz

Sea el sistema:

$$\begin{matrix}
4\, x_1 & - & 9\,x_2 & + & 2\,x_3 & = & 5\\
2\, x_1 & - & 4\,x_2 & + & 6\,x_3 & = & 3\\
 \, x_1 & - &  \,x_2 & + & 3\,x_3 & = & 4\\
\end{matrix}$$

1. Resuelva el sistema usando el método _solve_
2. Calcule el determinante de matriz de coeficientes usando el método _det_.
3. Resuelva el sistema usando la inversa de la matriz de coefientes.


In [11]:
# Resolviendo el sistema utilizando el método solve
A = np.array([[4,-9,2],[2,-4,6],[1,-1,3]])    # Matriz de coeficientes A
b = np.array([5,3,4])    # Vector b
x = np.linalg.solve(A,b)    # se llama a la operación solve para resolver el sistema

In [12]:
print x

[ 6.95  2.5  -0.15]


In [13]:
# calculando el determinante de la matriz de coefientes 
det_A = np.linalg.det(A)

In [14]:
print det_A

-19.999999999999996


Para resolver el sistema utilizando la inversa de A, se debe tomar en cuenta que:

$$\boldsymbol{x}=A^{-1}\boldsymbol{b}$$

In [15]:
# Resolviendo el sistema utilizando la inversa

inv_A = np.linalg.inv(A)    # Se calcula la inversa llamando a la operación inv

In [16]:
print inv_A    # Imprime la inversa calculada


[[ 0.3  -1.25  2.3 ]
 [ 0.   -0.5   1.  ]
 [-0.1   0.25 -0.1 ]]


In [17]:
"""
Para resolver el sistema hay que la realizar, A^-1 b, utilizando el método dot 
"""
x = np.dot(inv_A,b)

In [18]:
print x

[ 6.95  2.5  -0.15]


#### Sistemas de ecuaciones lineales especiales

+ Matrices simétricas
> Matriz cuadrada que tiene la característica de ser igual a su transpuesta.
$$A=A^{T}$$
$$a_{i,j} = a_{j,i}\, \text{para todo}\, i,\,j\,\text{con}\,i,\,j = 1,2,3,\ldots n $$
+ Matrices dispersas (gran número de sus elementos son cero)
> + Matrices dispersas bandeadas

>> + Diagonal

$$D = (d_{i,j}),\, \text{donde}\, d_{i,j} = 0\, \text{si}\, i\neq j $$

>> + Tridiagonal
 
$$\begin{bmatrix}
b_1 & c_1 &        &        & 0\\
a_2 & b_2 & c_2    &        &  \\
    & a_3 & b_3    & \ddots &  \\
    &     & \ddots & \ddots & c_{n-1} \\
0   &     &        & a_n    & b_{n} \\
\end{bmatrix} \, \begin{bmatrix}
x_1\\
x_2\\
\vdots\\
x_{n-1}\\
x_n
\end{bmatrix} = \begin{bmatrix}
d_1\\
d_2\\
\vdots\\
d_{n-1}\\
d_{n}
\end{bmatrix}$$

>> + Pentadiagonal

$${\begin{bmatrix}
c_{1}  & d_{1}  & e_{1}  & 0      & \cdots  & \cdots  & 0     \\
b_{1}  & c_{2}  & d_{2}  & e_{2}  & \ddots  &         & \vdots \\
a_{1}  & b_{2}  & \ddots & \ddots & \ddots  & \ddots  & \vdots \\
0      & a_{2}  & \ddots & \ddots & \ddots  & e_{n-3} & 0      \\
\vdots & \ddots & \ddots & \ddots & \ddots  & d_{n-2} & e_{n-2}\\
\vdots &        & \ddots & a_{n-3}& b_{n-2} & c_{n-1} & d_{n-1}\\
0      & \cdots & \cdots & 0      & a_{n-2} & b_{n-1} & c_{n}
\end{bmatrix}}$$

El paquete _sparse_ de la biblioteca _scipy_ permite resolver sistemas bandeados (dispersos):

+ **spsolve:** resuelve sistemas lineales dispersos de la forma $A\,\boldsymbol{x}=\boldsymbol{b}$, donde $\boldsymbol{b}$ puede ser un vector o una matriz.

Sea el sistema:

$$\begin{matrix}
3\, x_1 & - & 2\,    &   &          & = & 1.0\\
 \, x_1 & + & 5\,x_2 & - & 0.2\,x_3 & = & 5.8\\
 \,     &   & 4\,x_2 & + & 7\,x_3   & = & 11.0\\
\end{matrix}$$

 Resuelva el sistema usando los métodos _spsolve_.


In [19]:
from scipy.sparse import csc_matrix
from scipy.sparse.linalg import spsolve

"""
csc_matrix sirve para crear una matriz de columna dispersa comprimida, tal cual lo requiere 
el método spsolve.
"""
A = csc_matrix([[3,-2,0],[1,5,-0.2],[0,4,7]])    # Se crea la matriz A
b = np.array([1.0,5.8,11.0])

In [20]:
x =spsolve(A,b)    # Se resulve el sistema con el método spsolve

In [21]:
print x    # imprimimos la solución

[1. 1. 1.]


In [22]:
"""
Si se intenta enviar al método spsolve una matriz "A" creada con np.array, este devolverá un 
error indicando que spsolve requiere que la matriz "A" sea del tipo CSR o CSC:
"""
A = np.array([[3,-2,0],[1,5,-0.2],[0,4,7]])

In [23]:
x =spsolve(A,b)

C:\Users\Lap Cristobal\Anaconda2\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:133: SparseEfficiencyWarning: spsolve requires A be CSC or CSR matrix format
  SparseEfficiencyWarning)


**Otro ejemplo**

Sea el sistema:

$$\begin{matrix}
0.5 \, x_1 & + & 0.25\,x_2 &   &     \,    &   &             & = & 0.32\\
0.3 \, x_1 & + & 0.80\,x_2 & + & 0.40\,x_3 &   &             & = & 0.77\\
    \,     &   & 0.20\,x_2 & + &     \,x_3 & + & 0.60\,x_4   & = & -0.60\\
    \,     &   &     \,    &   &     \,x_3 & - & 3.0 \,x_4   & = & -2.0\\
\end{matrix}$$


In [24]:

A = csc_matrix([[0.5,0.25,0,0],[0.3,0.8,0.4,0],[0,0.2,1,0.6],[0,0,1,-3]])    
b = np.array([0.32,.77,-0.6,2])

In [25]:
x =spsolve(A,b)

In [26]:
print x

[ 0.08742857  1.10514286 -0.35085714 -0.78361905]


Para el caso de sistemas triangulares, el paquete _sparse_ posee el método _spsolve__triangular_. Sea el sistema:

$$\begin{matrix}
2 \, x_1 &   &  \,    &   &  \,      & = & -2\\
-3\, x_1 & + &  \,x_2 &   &  \,      & = &  7\\
 \,  x_1 & + & 4\,x_2 & - & 2\,x_3   & = & 11.0\\
\end{matrix}$$


In [27]:
from scipy.sparse import csr_matrix    # Permite crear matrices de fila dispersa comprimida
A = csr_matrix([[2, 0, 0], [-3, 1, 0], [1, 4, -2]], dtype=float)
b = np.array([-2,7,11])

In [28]:
from scipy.sparse.linalg import spsolve_triangular    # carga el método spsolve_triangular
x = spsolve_triangular(A,b)    # Se resuelve el sistema triangular inferior

In [29]:
print x    # Se muestra la solución del sistema 

[-1.  4.  2.]


#### Métodos de factorización o descomposición

+ **Factorización LU:** consiste en factorizar una matriz A, como el producto de una matriz triangular inferior (Lower) y una superior (Upper):


$$\begin{align*}
 A\,\boldsymbol{x}   &= \boldsymbol{b} \\
 L\,U\,\boldsymbol{x}&= \boldsymbol{b}  
\end{align*}$$

> Por ejemplo, para una matriz A de $3\times3$, se tiene:

$$\begin{bmatrix}
a_{1,1} & a_{1,2}  & a_{1,3}\\
a_{2,1} & a_{2,2}  & a_{2,3}\\
a_{3,1} & a_{3,2}  & a_{3,3}
\end{bmatrix} = 
\begin{bmatrix}
1       & 0       & 0\\
l_{2,1} & 1       & 0\\
l_{3,1} & l_{3,2} & 1
\end{bmatrix}\, 
\begin{bmatrix}
u_{1,1} & u_{1,2} & u_{1,3}\\
0       & u_{2,2} & u_{2,3}\\
0       & 0       & u_{3,3}
\end{bmatrix}$$

> Para resolver un sistema de ecuaciones por _Factorización LU_, se hace $U\boldsymbol{x}=\boldsymbol{c}$, donde $\boldsymbol{c}$ es un vector desconocido, que se obtiene resolviendo el sistema:

$$L\,\boldsymbol{c}=\boldsymbol{b}$$

> Una vez obtenido $\boldsymbol{c}$, se resuelve para $\boldsymbol{x}$:

$$U\,\boldsymbol{x}= c$$

>> El paquete _linalg_ de la biblioteca _scipy_ posee el método _lu__factor_, el cual permite calcular la descomposición LU de una matriz, en la forma:

$$A = P\,L\,U$$

>>Donde $P$ es una matriz de permutación (permutadora), L es la matriz triangular inferior con unos en la diagonal, y U es la matriz traingular superior.

>> La matriz permutadora $P$, es aquella cuyos elementos son ceros y unos (uno en cada fila o columna). Cuando se hace la operación $P\,A$, sirve para intercambiar las filas de $A$; en orden inverso $A\,P$, se intercambian las columnas de $A$. Por ejemplo, sea:

$$P = \begin{bmatrix}
0 & 1  & 0\\
1 & 0  & 0\\
0 & 0  & 1
\end{bmatrix}$$

$$A = \begin{bmatrix}
4 & -9  & 2\\
2 & -4  & 6\\
1 & -1  & 3
\end{bmatrix}$$



In [30]:
P = np.array([[0,1,0],[1,0,0],[0,0,1]])    # Matriz permutadora
A = np.array([[4,-9,2],[2,-4,6],[1,-1,3]])    # Matriz A

"""
El producto P A, sirve para intercambiar filas de A
"""
C = np.dot(P,A)
print C

[[ 2 -4  6]
 [ 4 -9  2]
 [ 1 -1  3]]


In [31]:
"""
En orden inverso 𝐴𝑃, se intercambian las columnas de 𝐴
"""
D = np.dot(A,P)
print D

[[-9  4  2]
 [-4  2  6]
 [-1  1  3]]


Sea el sistema:

$$\begin{matrix}
4\, x_1 & - & 9\,x_2 & + & 2\,x_3 & = & 5\\
2\, x_1 & - & 4\,x_2 & + & 6\,x_3 & = & 3\\
 \, x_1 & - &  \,x_2 & + & 3\,x_3 & = & 4\\
\end{matrix}$$

+ Resuelva el sistema usando factorización LU.


In [32]:
from scipy.linalg import lu_factor    # Carga el método lu_factor

b = np.array([5,3,4])    # Creamos el vector b; la matriz A fue creada en el ejemplo anterior

In [33]:
# Enviamos la matriz al método lu_factor; 
LU = lu_factor(A)    

In [34]:
print LU    # Imprimimos la matriz permutadora

(array([[ 4.  , -9.  ,  2.  ],
       [ 0.25,  1.25,  2.5 ],
       [ 0.5 ,  0.4 ,  4.  ]]), array([0, 2, 2]))


In [35]:
"""
Una vez obtenido LU, se utiliza el método lu_solve del paquete linalg
"""

from scipy.linalg import lu_solve    # Permite resolver sistemas por LU

x =lu_solve(LU,b)     

print x    # Imprimimos la solución

[ 6.95  2.5  -0.15]


+ **Método de Doolite y Crout:** 

### Métodos iterativos