## Independencia y ortogonalización de vectores



### Combinación lineal

$$\alpha_1 x_1 + \alpha_2 x_2 + \ldots + \alpha_n x_n$$

donde $\alpha_1,\alpha_2,\ldots,\alpha_n$ son números reales y $x_1,x_2,\ldots,x_n$ son vectores de $m$ elementos cada uno.

### Dependencia lineal

Se dice que un vector $x = [x_1, x_2,… x_m]^T$, depende linealmente de un conjunto de vectores de $m$ elementos $x_1, x_2,\ldots x_n$, si se pueden encontrar escalares $\alpha_1,\alpha_2,\ldots,\alpha_n$, tales que se cumpla la siguiente ecuación
vectorial

$$x = \alpha_1 x_1 + \alpha_2 x_2 + \ldots + \alpha_n x_n$$

Si no existen escalares que satisfagan tal ecuación, $x$ es un vector linealmente independiente de $x_1,x_2,\ldots,x_n$. En otras palabras, $x$ es linealmente dependiente de $x_1,x_2,\ldots,x_n$ si y sólo si $x$ es una combinación lineal de $x_1,x_2,\ldots,x_n$.

**Ejemplo**: Dado el conjunto de dos vectores de dos elementos

$$x_1 = [4,4]^T$$
$$x_2 = [-2,2]^T$$

demuestre que el vector $x^T = [ 0, 8 ]^T$ es linealmente dependiente de dicho conjunto.

In [ ]:
import numpy as np

x_1 = np.array([4,4])
x_2 = np.array([-2,2])
x = np.array([0,8])

In [ ]:
alfa_1, alfa_2 = 1,2
(alfa_1*x_1 + alfa_2*x_2 == x).all()

True

¿Por qué se usó $\alpha_1 = 1$ y $\alpha_2 = 2$?

In [ ]:
np.array([x_1,x_2])

array([[ 4,  4],
       [-2,  2]])

In [ ]:
A = np.array([x_1,x_2]).transpose()
A

array([[ 4, -2],
       [ 4,  2]])

In [ ]:
alfas = np.dot(np.linalg.inv(A),x)
print(alfas)

[1. 2.]


In [ ]:
# Otra manera de resolver es usando el método solve
np.linalg.solve(A,x)

array([1., 2.])

### Vectores ortogonales

Dos vectores de igual número de componentes son ortogonales o perpendiculares si el coseno del ángulo entre ellos es cero. De acuerdo con esta definición, el vector cero es ortogonal con cualquier otro vector; en general, $\vec{x}$ y $\vec{y}$ son ortogonales si y sólo si

$$\vec{x}\cdot \vec{y} = x_1 y_1 + x_2 y_2 + \ldots + x_n y_n$$

$$\vec{x}\cdot \vec{y} = |x|\,|y|\cos\theta$$

**Ejemplo**: Determine si los vectores $\vec{x_1} = (4,4)$ y $\vec{x_2}=(-2,2)$ son ortogonales.

In [ ]:
x_1 = np.array([4,4])
x_2 = np.array([-2,2])

In [ ]:
if np.dot(x_1,x_2)==0:
  print("x_1 y x_2 son ortogonales")
else:
  print("x_1 y x_2 no son ortogonales")

x_1 y x_2 son ortogonales


**Ejemplo**: Determine si los vectores $\vec{x_1} = (1,0,0,0)$, $\vec{x_2}=(0,1,0,0)$ y $\vec{x_3}=(0,0,1,0)$ son ortogonales.

In [ ]:
x_1 = np.array([1,0,0,0])
x_2 = np.array([0,1,0,0])
x_3 = np.array([0,0,1,0])

In [ ]:
if np.dot(x_1,x_2)==0 and np.dot(x_1,x_3)==0 and np.dot(x_2,x_3)==0:
  print("x_1, x_2 y x_3 son ortogonales")
else:
  print("x_1, x_2 y x_3 no son ortogonales")

x_1, x_2 y x_3 son ortogonales


**Ejemplo**: Determine si los vectores $\vec{x_1} = (1,0,0,0)$, $\vec{x_2}=(0,1,0,0)$, $\vec{x_3}=(0,0,1,0)$  y $\vec{x_4}=(2,1,0,0)$son ortogonales.

In [ ]:
x_1 = np.array([1,0,0,0])
x_2 = np.array([0,1,0,0])
x_3 = np.array([0,0,1,0])
x_4 = np.array([2,1,0,0])

In [ ]:
conjunto = np.array([np.dot(x_1,x_2), np.dot(x_1,x_3), np.dot(x_1,x_4), 
                     np.dot(x_2,x_3), np.dot(x_2,x_4),np.dot(x_3,x_4)])

if (conjunto == np.zeros_like(conjunto)).all():
  print("El conjunto es ortogonal")
else:
  print("El conjunto no es ortogonal")

El conjunto no es ortogonal


### Criterio de ortogonalización

Corrobore si $\vec{x_1} = (-3,4,1)$ y $\vec{x_2} = (2,2,-2.0003)$ son ortogonales.


In [ ]:
x_1 = np.array([-3,4,1])
x_2 = np.array([2,2,-2.0003])
np.dot(x_1,x_2)

-0.000300000000000189

Obsérvese que los vectores son "casi" ortogonales. Esto ocurre con frecuencia, y en los cálculos prácticos será preciso decidir con qué cercanía a cero se aceptará que un producto punto de dos vectores “es cero” y, por lo tanto, que los vectores son ortogonales.

In [ ]:
if abs(np.dot(x_1,x_2)) <= 0.0001:
  print("El conjunto es ortogonal")
else:
  print("El conjunto no es ortogonal")

El conjunto no es ortogonal


Con $\epsilon = 10^{–4} $ los vectores de este ejemplo no son ortogonales. Así pues, $\epsilon$ usado de esta manera puede llamarse *criterio de ortogonalidad**.

### Ortogonalización

La ortogonalización permite construir un conjunto de vectores ortogonales a partir de un conjunto de vectores linealmente independientes.

#### Método de Gram-Schmidt

Sea $\vec{x_1}$ y $\vec{x_2}$ dos vectores linealmente independientes

<img src="https://drive.google.com/uc?id=1eICDh-a1coVMaK-gd4CmDqLHLVj_IdE8&export=download" width="100%">

Se toma $e_1 = \vec{x_1}$ y $e_2$ como la componente de $\vec{x_2}$ perpendicular a $\vec{x_1}$.

De tal manera que

$$e_2 = \vec{x_2}-\alpha_{1,2}e_1$$

Para determinar $\alpha_{1,2}$ se debe cumplir la condición $e_1\cdot e_2=0$. Por lo tanto:

$$e_1\cdot e_2 = 0 = \vec{x_2}\cdot e_1 - \alpha_{1,2}e_{1}\cdot e_1$$

por lo que 

$$\alpha_{1,2}=\dfrac{\vec{x_2}\cdot e_1}{e_1\cdot e_1}$$

**Ejemplo**: Ortogonalice $\vec{x_1}=(2,2)$ y $\vec{x_2}=(3,0)$


In [ ]:
x_1 = np.array([2,2])
x_2 = np.array([3,0])

In [ ]:
e_1 = np.copy(x_1)
e_1

array([2, 2])

In [ ]:
alfa_12 = np.dot(x_2,e_1)/np.dot(e_1,e_1)
alfa_12

0.75

In [ ]:
e_2 = x_2 - alfa_12*e_1
e_2

array([ 1.5, -1.5])

**Ejemplo**: Ortogonalice $\vec{x_1} = (1,1,0)$, $\vec{x_2} = (0,1,0)$ y $\vec{x_3} = (1,1,1)$

$$\begin{align*}
e_1 &= \vec{x_1}\\
e_2 &= \vec{x_2}-\alpha_{1,2}e_1\\
e_3 &= \vec{x_3}-\alpha_{1,3}e_1 -\alpha_{2,3}e_2 
\end{align*}$$

$$\begin{align*}
\alpha_{1,2}&=\dfrac{\vec{x_2}\cdot e_1}{e_1\cdot e_1}\\
\alpha_{1,3}&=\dfrac{\vec{x_3}\cdot e_1}{e_1\cdot e_1}\\
\alpha_{2,3}&=\dfrac{\vec{x_3}\cdot e_2}{e_2\cdot e_2}
\end{align*}$$

In [ ]:
x_1 = np.array([1,1,0])
x_2 = np.array([0,1,0])
x_3 = np.array([1,1,1])

In [ ]:
e_1 = np.copy(x_1)
alfa_12 = np.dot(x_2,e_1)/np.dot(e_1,e_1)
alfa_13 = np.dot(x_3,e_1)/np.dot(e_1,e_1)
print(alfa_12,alfa_13)

0.5 1.0


In [ ]:
e_2 = x_2 - alfa_12*e_1
e_2

array([-0.5,  0.5,  0. ])

In [ ]:
alfa_23 = np.dot(x_3,e_2)/np.dot(e_2,e_2)
alfa_23

0.0

In [ ]:
e_3 = x_3 - alfa_13*e_1 - alfa_23*e_2
e_3

array([0., 0., 1.])

**Generalizando el método de Gram-Schmidt para un conjunto de $n$ vectores**

Para un conjunto de $n$ vectores $\vec{x_1}, \vec{x_2},\ldots, \vec{x_n}$ linealmente independientes con $n$ componentes cada uno. Se puede construir un conjunto ortogonal $\vec{e_1}, \vec{e_2},\ldots,\vec{e_n}$ de la siguiente manera:

> **Paso 1**: Hacer $\vec{e_1} = \vec{x_1}$

> **Paso 2**:  Hacer para cada $i+1$ vector del conjunto

$$\vec{e_{i+1}}= \vec{x_{i+1}} - \alpha_{1,i+1}\vec{e_1} - \ldots - \alpha_{i,i+1}\vec{e_i}\quad 1\leq i\leq n-1$$

>> donde

$$\begin{align*}
\alpha_{1,i+1} &= \dfrac{\vec{x_{i+1}}\cdot\vec{e_1}}{\vec{e_1}\cdot\vec{e_1}}\\
\alpha_{2,i+1} &= \dfrac{\vec{x_{i+1}}\cdot\vec{e_2}}{\vec{e_2}\cdot\vec{e_2}}\\
\alpha_{i,i+1} &= \dfrac{\vec{x_{i+1}}\cdot\vec{e_i}}{\vec{e_i}\cdot\vec{e_i}}
\end{align*}$$


**Tarea**: Ortogonalice el siguiente conjunto de vectores linealmente independientes.

$$\begin{align*}
\vec{x_1} &= (2,0,1)\\
\vec{x_2} &= (3,2,0)\\
\vec{x_3} &= (1,1,1)
\end{align*}$$



## Independencia de conjuntos de vectores

Un conjunto de vectores dado $y_1, y_2,\ldots,y_n$, es linealmente dependiente si por lo menos uno de ellos es combinación lineal de alguno o de todos los vectores restantes. Si ninguno lo es, se dice que es un conjunto linealmente independiente

**Ejemplo**: Sea el siguiente conjunto de cuatro vectores de tres elementos cada uno.

$$y_1 = [1,4,2],\,y_2 = [0.1,-3,0],\,y_3 = [0.5,-15,0],\,y_4 = [0.03,-0.9,0]$$

Determine si es linealmente dependiente o independiente.

In [ ]:
y1 = np.array([1,4,2])
y2 = np.array([0.1,-3.0,0])
y3 = np.array([0.5,-15,0])
y4 = np.array([0.03,-0.9,0])

In [ ]:
A = np.array([y1,y2,y3,y4]).transpose()
A

array([[  1.  ,   0.1 ,   0.5 ,   0.03],
       [  4.  ,  -3.  , -15.  ,  -0.9 ],
       [  2.  ,   0.  ,   0.  ,   0.  ]])

In [ ]:
b = np.zeros(3)
b

array([0., 0., 0.])

In [ ]:
np.linalg.solve(A,b)

LinAlgError: ignored

### Rango de una matriz
El rango de una matriz es el número de filas (o columnas) linealmente independientes.

In [ ]:
rank = np.linalg.matrix_rank(A)
rank

In [ ]:
y3==5*y2

In [ ]:
y4

In [ ]:
0.3*y2

**Ejemplo**: Determinen el rango de la matriz $A$.

$$A = \begin{bmatrix}
0 & 0 & 1\\
5 & 1 & 1\\
5 & 1 & 1\\
0 & 0 & 1
\end{bmatrix}$$

In [ ]:
A = np.array([[0,0,1],[5,1,1],[5,1,1],[0,0,1]])
np.linalg.matrix_rank(A)

Otro forma:

In [ ]:
np.linalg.det([[0,0,1],[5,1,1],[5,1,1]])

In [ ]:
np.linalg.det([[5,1,1],[5,1,1],[0,0,1]])

In [ ]:
np.linalg.det([[0,5],[1,1]])

### Matriz singular o mal condicionada

Cuando el rango de una matriz cuadrada de orden $n$ es menor que $n$, se dice que la matriz es singular. Esto significa también que su determinante es cero. Si las columnas de la matriz son "casi" linealmente dependientes, recibe el nombre de casi singular o mal condicionada.

## Solución de sistemas de ecuaciones lineales

Si recordamos, en el **Paso 2** del algoritmo de Newton Raphson para sistemas de ecuaciones _no lineales_,  se tiene que resolver un sistema de ecuacioes lineales que se construye a partir de las funciones y del jacobiano de las funciones no lineales. Muchos de los problemas en ingeniería se reducen a resolver un sistema de ecuaciones lineales.

Un sistema de $m$ ecuaciones lineales en $n$ incoógnitas tiene la forma:

$$\begin{matrix}
a_{1,1}x_1 & + & a_{1,2}x_2 & + & \ldots & + & a_{1,n}x_n & = & b_1\\
a_{2,1}x_1 & + & a_{2,2}x_2 & + & \ldots & + & a_{1,n}x_n & = & b_1\\
\vdots &   &       \vdots   & + &        &   & \vdots               \\
a_{m,1}x_1 & + & a_{m,2}x_2 & + & \ldots & + & a_{m,n}x_n & = & b_m\\
\end{matrix}$$

en notación matricial:

$$\begin{align*}
\begin{bmatrix}
a_{1,1} &  a_{1,2} &  \ldots &  a_{1,n}  \\
a_{2,1} &  a_{2,2} &  \ldots &  a_{1,n}  \\
\vdots  &  \vdots  &         &  \vdots   \\
a_{m,1} &  a_{m,2} &  \ldots &  a_{m,n} \\
\end{bmatrix}\, \begin{bmatrix}
x_1\\
x_2\\
\vdots\\
x_m
\end{bmatrix} &= \begin{bmatrix}
b_1\\
b_2\\
\vdots\\
b_m
\end{bmatrix}\\
A\,\boldsymbol{x}&=\boldsymbol{b}
\end{align*}$$

### Matriz aumentada $B$

Se forma con los elementos de la matriz de coefientes $A$ y los del vector $\boldsymbol{b}$.

$$
B = \left[
\begin{array}{cccc|c}
a_{1,1} & a_{1,2} & \ldots & a_{1,n} & b_{1}\\
a_{2,1} & a_{2,2} & \ldots & a_{2,n} & b_{2}\\
\vdots  & \vdots  &        & \vdots  & \vdots\\
a_{m,1} & a_{m,2}0 & \ldots & a_{m,n} & b_{m}\\
\end{array}
\right] = \left[\begin{array}{c|c}A&\boldsymbol{b}\end{array} \right]
$$

+ Si $\boldsymbol{b}=\boldsymbol{0}$ es un _sistema homogéneo_
+ si $\boldsymbol{b}\neq \boldsymbol{0}$ es un _sistema no homogéneo_ 
+ Si el rango de $A$ es igual al rango de $B$, el sistema es _consistente_
> + Un sistema consistente puede tener una solución o un número infinito de soluciones.
>> + Si $Rango\,A = n$, donde $n$ es el número de incógnitas, la solución es única.
>> + Si $Rango\,A < n$, hay un número infinito de soluciones.
+ Si el rango de $A$ es diferente al rango de $B$, el sistema es _inconsistente_
> + Un sistema inconsistente **no tiene solución**.

**Rango:** es el número de columnas o filas que son linealmente independientes. El rango fila y el rango columna siempre son iguales.

**Independencia lineal:** dado un conjunto de vectores $\boldsymbol{v_1},\, \boldsymbol{v_2},\,\ldots,\boldsymbol{v_n}$ se dice que son _linealmente independientes_ si :

$$a_1\boldsymbol{v_1} + a_2\boldsymbol{v_2} + \ldots + a_n\boldsymbol{v_n} = \boldsymbol{0} $$

se satiface únicamente cuando $a_1,\, a_2,\,\ldots,a_n $ son todos cero. De lo contrario, se dice qee son linealmente dependientes.


Python permite calcular el rango de una matriz, para ello, es necesario cargar la bilbioteca numpy,
para poder utilizar los método (o funciones) array y rank. Sea el sistema:


$$\begin{matrix}
2\, x_1 & + & 4\,x_2 &  = & 6\\
3\, x_1 & + & 6\,x_2 &  = & 5\\
\end{matrix}$$

Calcular el rango de $A$ y de $B$

In [ ]:
A = np.array([[2, 4],[3,6]])    # Con array se crea la matriz A
m, n = A.shape
B = np.array([[2,4,6],[3,6,5]])    # Se crea la matriz B
b = np.array([6,5])
rango_A = np.linalg.matrix_rank(A)    
rango_B = np.linalg.matrix_rank(B)

if rango_A == rango_B:
  if rango_A == n:
    np.linalg.solve(A,b)
  elif rango_A < n:
    print("El sistema tiene un numero infinito de soluciones")
else:
  print("El sistema es inconsistente")

Si el sistema fuera homogéneo, el rango de $A$ es igual al rango de $B$; de hecho un sistema homogéneo siempre es consistente. 

$$\begin{matrix}
2\, x_1 & + & 4\,x_2 &  = & 0\\
3\, x_1 & + & 6\,x_2 &  = & 0\\
\end{matrix}$$

In [ ]:
A = np.array([[2, 4],[3,6]])
B = np.array([[2,4],[3,6]])

rango_A = np.linalg.matrix_rank(A)    
rango_B = np.linalg.matrix_rank(B)

rango_A == rango_B

In [ ]:
if rango_A == rango_B:
  if rango_A == n:
    np.linalg.solve(A,b)
  elif rango_A < n:
    print("El sistema tiene un numero infinito de soluciones")
else:
  print("El sistema es inconsistente")

### Operaciones elementales

+ Cambiar entre sí dos filas, o en su caso columnas.
+ Multiplicar una fila(columna) por un número real distinto de cero.
+ Sumar a una fila(columna) otra fila(columna) multiplicada por un número real.


### Métodos directos de solución

+ Eliminación Gaussiana

Sea el sistema: 

$$\begin{matrix}
a_{1,1}\, x_1 & + & a_{1,2}\,x_2 & + & a_{1,3}\,x_3 & = & b_1\\
a_{2,1}\, x_1 & + & a_{2,2}\,x_2 & + & a_{2,3}\,x_3 & = & b_2\\
a_{3,1}\, x_1 & + & a_{3,2}\,x_2 & + & a_{3,3}\,x_3 & = & b_3\\
\end{matrix}$$

Se realizan las operaciones elementales de multiplicación y suma hasta llegar a la _triangulización_ del sistema (triangular superior):

$$\begin{matrix}
a_{1,1}\, x_1 & + & a_{1,2}\,x_2 & + & a_{1,3}\,x_3 & = & b_1\\
              &   & a_{2,2}^{\prime\prime}\,x_2 & + & a_{2,3}^{\prime\prime}\,x_3 & = & b_2^{\prime\prime}\\
              &   &                       &   & a_{3,3}^{\prime\prime}\,x_3 & = & b_3^{\prime\prime}\\
\end{matrix}$$

Para resolver el sistema triangulizado, se aplica _sustitución regresiva_.

Una vez triangulizado el sistema, se puede calcular el _determinante_ de la matriz $A$ del sistema original.

$$\text{det} A = \prod_{i=1}^{n}{a_{i,i}}= a_{1,1}\,a_{2,2}\ldots a_{n,n}$$

+ Eliminación Gauss con pivoteo parcial

Se selecciona como pivote el coeficiente de máximo valor absoluto en la columna relevante de la matriz. Se toman las columnas como en el método gaussiano, de modo que se vayan eliminando las incógnitas $(x_1,\,x_2,\ldots,x_n)$ en orden natural.

+ Eliminación Gauss-Jordan

Este método continúa el proceso de triangulización, desde triangular superior hasta obtener una matriz diagonal, y por tanto, no se requiere la sustitución regresiva.

> + Inversa de una matriz por Gauss-Jordan

>> + La inversa $(A^{-1})$ de una matriz $(A)$, es aquella aquella que al multiplicarla por la matriz original $(A)$, el resultado es la matriz identidad $(I)$.

$$A\,A^{-1}=A^{-1}\,A=I$$

>> + Para que exista la inversa de una matriz, su determinante debe ser distinto de cero.

$$\text{det}A \neq 0$$

>> + Para calcular la inversa, en una misma matriz se coloca en la parte izquierda la matriz $A$, y en la parte derecha la identidad $I$:

$$\left[A|I\right]$$

>>> Se aplica el método de Gauss-Jordan hasta conseguir que en la parte izquierda quede la matriz identidad $(I)$, la matriz resulante en la parte derecha, será la matriz inversa $(A^{-1})$:

$$\left[A|I\right]\xrightarrow{Gauss-Jordan}\left[I|A^{-1}\right]$$

La biblioteca _Numpy_ posee el paquete _linalg_, el cual contiene métodos que permiten resolver sistemas de ecuaciones lineales, calcular el determinante y la inversa de una matriz:

+ **solve:** resuelve sistemas de ecuaciones lienales (consistente) de la forma $A\,\boldsymbol{x}=\boldsymbol{b}$

+ **inv:** permite calcular la inversa de una matriz

+ **det:** calcula el determinante de una matriz

Sea el sistema:

$$\begin{matrix}
4\, x_1 & - & 9\,x_2 & + & 2\,x_3 & = & 5\\
2\, x_1 & - & 4\,x_2 & + & 6\,x_3 & = & 3\\
 \, x_1 & - &  \,x_2 & + & 3\,x_3 & = & 4\\
\end{matrix}$$

1. Resuelva el sistema usando el método _solve_
2. Calcule el determinante de matriz de coeficientes usando el método _det_.
3. Resuelva el sistema usando la inversa de la matriz de coefientes.

In [ ]:
# Resolviendo el sistema utilizando el método solve
A = np.array([[4,-9,2],[2,-4,6],[1,-1,3]])    # Matriz de coeficientes A
b = np.array([5,3,4])    # Vector b
x = np.linalg.solve(A,b)    # se llama a la operación solve para resolver el sistema

In [ ]:
print(x)

In [ ]:
# calculando el determinante de la matriz de coefientes 
det_A = np.linalg.det(A)

In [ ]:
print(det_A)

Para resolver el sistema utilizando la inversa de A, se debe tomar en cuenta que:

$$\boldsymbol{x}=A^{-1}\boldsymbol{b}$$

In [ ]:
# Resolviendo el sistema utilizando la inversa

inv_A = np.linalg.inv(A)    # Se calcula la inversa llamando a la operación inv

In [ ]:
print(inv_A)

In [ ]:
"""
Para resolver el sistema hay que la realizar, A^-1 b, utilizando el método dot 
"""
x = np.dot(inv_A,b)

In [ ]:
print(x)

#### Sistemas de ecuaciones lineales especiales

+ Matrices simétricas
> Matriz cuadrada que tiene la característica de ser igual a su transpuesta.
$$A=A^{T}$$
$$a_{i,j} = a_{j,i}\, \text{para todo}\, i,\,j\,\text{con}\,i,\,j = 1,2,3,\ldots n $$
+ Matrices dispersas (gran número de sus elementos son cero)
> + Matrices dispersas bandeadas

>> + Diagonal

$$D = (d_{i,j}),\, \text{donde}\, d_{i,j} = 0\, \text{si}\, i\neq j $$

>> + Tridiagonal
 
$$\begin{bmatrix}
b_1 & c_1 &        &        & 0\\
a_2 & b_2 & c_2    &        &  \\
    & a_3 & b_3    & \ddots &  \\
    &     & \ddots & \ddots & c_{n-1} \\
0   &     &        & a_n    & b_{n} \\
\end{bmatrix} \, \begin{bmatrix}
x_1\\
x_2\\
\vdots\\
x_{n-1}\\
x_n
\end{bmatrix} = \begin{bmatrix}
d_1\\
d_2\\
\vdots\\
d_{n-1}\\
d_{n}
\end{bmatrix}$$

>> + Pentadiagonal

$${\begin{bmatrix}
c_{1}  & d_{1}  & e_{1}  & 0      & \cdots  & \cdots  & 0     \\
b_{1}  & c_{2}  & d_{2}  & e_{2}  & \ddots  &         & \vdots \\
a_{1}  & b_{2}  & \ddots & \ddots & \ddots  & \ddots  & \vdots \\
0      & a_{2}  & \ddots & \ddots & \ddots  & e_{n-3} & 0      \\
\vdots & \ddots & \ddots & \ddots & \ddots  & d_{n-2} & e_{n-2}\\
\vdots &        & \ddots & a_{n-3}& b_{n-2} & c_{n-1} & d_{n-1}\\
0      & \cdots & \cdots & 0      & a_{n-2} & b_{n-1} & c_{n}
\end{bmatrix}}$$

El paquete _sparse_ de la biblioteca _scipy_ permite resolver sistemas bandeados (dispersos):

+ **spsolve:** resuelve sistemas lineales dispersos de la forma $A\,\boldsymbol{x}=\boldsymbol{b}$, donde $\boldsymbol{b}$ es un vector.

Sea el sistema:

$$\begin{matrix}
3\, x_1 & - & 2\,    &   &          & = & 1.0\\
 \, x_1 & + & 5\,x_2 & - & 0.2\,x_3 & = & 5.8\\
 \,     &   & 4\,x_2 & + & 7\,x_3   & = & 11.0\\
\end{matrix}$$

 Resuelva el sistema usando los métodos _spsolve_.

##### Método de Thomas para sistemas tridiagonales
Sea el sistema:

$$\begin{matrix}
b_1\, x_1  & + & c_1\,x_2 &   &  & = & d_1\\
a_2\,x_1 & + & b_2\,x_2 & + & c_2\,x_3 & = & d_2\\
         &   & a_3\,x_2 & + & b_3\,x_3 & = & d_3\\
\end{matrix}$$

**Aplicando el método de Gauss**

> Si $b_1\neq 0$, se elimina $x_1$ sólo en la segunda ecuación.

$$F_2  = F_2 - \dfrac{a_2}{b_1}F_1$$

$$\begin{align*} 
(a_2x_1 - \dfrac{a_2}{b_1}b_1x_1) + b_2x_2 - (\dfrac{a_2}{b_1}c_1x_2 ) + c_2x_3 = d_2-\dfrac{a_2}{b_1}d_1\\
b_2x_2 - (\dfrac{a_2}{b_1}c_1x_2 ) + c_2x_3 = d_2-\dfrac{a_2}{b_1}d_1
\end{align*}$$



El nuevo sistema es:

$$\begin{matrix}
b_1\, x_1  & + & c_1\,x_2 &   &  & = & d_1\\
           &   & b^{'}_2\,x_2 & + & c^{'}_2\,x_3 & = & d^{'}_2\\
         &   & a_3\,x_2 & + & b_3\,x_3 & = & d_3\\
\end{matrix}$$

donde 
$$\begin{align*}
b^{'}_{2}&= b_2 - \dfrac{a_2}{b_1}c_1\\
c^{'}_2 &= c_2\\
d^{'}_2 &= d_2 - \dfrac{a_2}{b_1}d_1
\end{align*}$$

> Si $b^{'}_2\neq 0$, $x_2$ se elimina sólo de la tercera ecuación.

$$F_3 = F_3 - \dfrac{a_3}{b^{'}_2}F_2$$

$$\begin{align*}
a_3x_2 + b_3x_3 &= d_3\\
(a_3x_2 - \dfrac{a_3}{b^{'}_2}b^{'}_2x_2) + (b_3\,x_3 - \dfrac{a_3}{b^{'}_2}c^{'}_2x_3) &= (d_3 - \dfrac{a_3}{b^{'}_2}d^{'}_2) \\
(b_3\,x_3 - \dfrac{a_3}{b^{'}_2}c^{'}_2x_3) &= (d_3 - \dfrac{a_3}{b^{'}_2}d^{'}_2)
\end{align*}$$

El nuevo sistema es:

$$\begin{matrix}
b_1\, x_1  & + & c_1\,x_2 &   &  & = & d_1\\
           &   & b^{'}_2\,x_2 & + & c^{'}_2\,x_3 & = & d^{'}_2\\
         &   &  &  & b^{'}_3\,x_3 & = & d^{'}_3\\
\end{matrix}$$

donde 
$$\begin{align*}
b^{'}_{3}&= b_3 - \dfrac{a_3}{b^{'}_2}c^{'}_2\\
d^{'}_3 &= d_3 - \dfrac{a_3}{b^{'}_2}d^{'}_2
\end{align*}$$


In [ ]:
# Método de Thomas
a = np.array([0,1,4])
b = np.array([3,5,7])
c = np.array([-2,-0.2,0])
d = np.array([1.0,5.8,11.0])
N = a.shape[0]
x = np.zeros_like(a)

for i in range(1,N):
  m = a[i-1]/b[i-1]
  b[i] = b[i] - m*c[i-1]
  d[i] = d[i] - m*d[i-1]
   
x[-1] = d[-1]/b[-1]
for i in range(N-2,-1,-1):
  x[i] = (d[i] - c[i]*x[i+1])/b[i]

print(x)

In [ ]:
from scipy.sparse import csc_matrix
from scipy.sparse.linalg import spsolve

"""
csc_matrix sirve para crear una matriz de columna dispersa comprimida, tal cual lo requiere 
el método spsolve.
"""
A = csc_matrix([[3,-2,0],[1,5,-0.2],[0,4,7]])    # Se crea la matriz A
b = np.array([1.0,5.8,11.0])

In [ ]:
x =spsolve(A,b)    # Se resulve el sistema con el método spsolve
x

### Métodos de factorización



#### Factorización de matrices en matrices triangulares

Sea el sistema:

$$\begin{matrix}
4\, x_1 & - & 9\,x_2 & + & 2\,x_3 & = & 5\\
2\, x_1 & - & 4\,x_2 & + & 6\,x_3 & = & 3\\
 \, x_1 & - &  \,x_2 & + & 3\,x_3 & = & 4\\
\end{matrix}$$

Aplicando eliminación Gaussiana sin hacer 1 los elementos de la diagonal principal, se tiene el siguiente sistema equivalente: 

$$\left[
\begin{array}{ccc|c}
4 & -9 & 2 & 5\\
0 & 0.5 & 5 & 0.5\\
0 & 0 & -10 & 1.5\\
\end{array}
\right]$$

A la matriz de coeficientes del sistema anterior se le denotará como $U$

$$U = \left[
\begin{array}{ccc}
4 & -9 & 2  \\
0 & 0.5 & 5 \\
0 & 0 & -10\\
\end{array}
\right]$$

Ahora se define una matriz triangular inferior $L$ del mismo orden que $A$, con $1$ en la diagonal principal y con $l_{i,j}$ igual al factor (cociente) que permitió eliminar el elemento $a_{i,j}$ que dio lugar a $U$. Por ejemplo, para hacer $0$ a $a_{2,1} = 2$ se utilizó el cociente $l_{2,1}=2/4$.

$$L = \left[
\begin{array}{ccc}
1 & 0 & 0  \\
\frac{2}{4} & 1 & 0 \\
\frac{1}{4} & \frac{1.25}{0.5} &1\\
\end{array}
\right]$$

El producto de $LU$ resulta en $A$

In [ ]:
A = np.array([[4,-9,2],[2,-4,6],[1,-1,3]]) 
U = np.array([[4,-9,2],[0,0.5,5],[0,0,-10]])
L = np.array([[1,0,0],[2/4,1,0],[1/4,1.25/0.5,1]])
np.dot(L,U)

In [ ]:
np.allclose(A,np.dot(L,U))

In [ ]:
np.allclose(A-np.dot(L,U),np.zeros_like(A))

El resultado anterior permite reescribir el sistema $A\boldsymbol{x} = \boldsymbol{b}$, ya que sustituyendo $A$ por $L U$ se tiene

$$\begin{align*}
LU\boldsymbol{x}&=\boldsymbol{b}\\
\end{align*}$$

Para resolver el sistema:

> **Paso 1:** se hace $U\boldsymbol{x} = \boldsymbol{c}$, donde $\boldsymbol{c}$ es un vector desconocido $[c_1,c_2,c_3,\ldots,c_n]^T$ que se obtiene al resolver 

$$L\boldsymbol{c}=\boldsymbol{b}$$

> con sustitución progresiva hacia adelante.

> **Paso 2**: Una vez obtenido $\boldsymbol{c}$, se resuelve para $\boldsymbol{x}$

$$U\boldsymbol{x}=\boldsymbol{c}$$

> con sustitución regresiva.

#### Factorización Doolitle y Crout

Analizando la factorización de $A$

$$\left[
\begin{array}{ccc}
l_{1,1} & 0 & 0 \\
l_{2,1} & l_{2,2} & 0 & \\
l_{3,1} & l_{3,3} & l_{3,3} & \\
\end{array}
\right] \left[
\begin{array}{ccc}
U_{1,1} & U_{1,2} & U_{1,3}\\
0       & U_{2,2} & U_{2,3} & \\
0       & 0       & U_{3,3} & \\
\end{array}
\right] = \left[
\begin{array}{ccc}
a_{1,1} & a_{1,2} & a_{1,3}\\
a_{2,1} & a_{2,2} & a_{2,3} & \\
a_{3,1} & a_{3,2} & a_{3,3} & \\
\end{array}
\right]$$

se observa que:

> $a_{1,1}, a_{1,2}$ y $a_{1,3}$, es decir la $F^A_1$, se obtiene al multiplicar $F^L_1$ por cada una de las columnas de $U$.

$$\begin{align*}
\text{Sistema 1}\\
l_{1,1}u_{1,1} &= a_{1,1}\\
l_{1,1}u_{1,2} &= a_{1,2}\\
l_{1,1}u_{1,3} &= a_{1,3}\\
\end{align*}$$

> $a_{2,1}, a_{2,2}$ y $a_{2,3}$, es decir la $F^A_2$, se obtiene al multiplicar $F^L_2$ por cada una de las columnas de $U$.

$$\begin{align*}
\text{Sistema 2}\\
l_{2,1}u_{1,1} &= a_{2,1}\\
l_{2,1}u_{1,2} + l_{2,2}u_{2,2}  &= a_{2,2}\\
l_{2,1}u_{1,3} + l_{2,2}u_{2,3}&= a_{2,3}\\
\end{align*}$$

> > $a_{3,1}, a_{3,2}$ y $a_{3,3}$, es decir la $F^A_3$, se obtiene al multiplicar $F^L_3$ por cada una de las columnas de $U$.

$$\begin{align*}
\text{Sistema 3}\\
l_{3,1}u_{1,1} &= a_{3,1}\\
l_{3,1}u_{1,2} + l_{3,2}u_{2,2}  &= a_{3,2}\\
l_{3,1}u_{1,3} + l_{3,2}u_{2,3} + l_{3,3}u_{3,3}&= a_{3,3}\\
\end{align*}$$

Se llega a un sistema de nueve ecuaciones con 12 incógnitas.
> Si se toma $l_{1,1} = l_{2,2} = l_{3,3} = 1$ se obtiene el método de Doolitle.

> Si se toma $U_{1,1} = U_{2,2} = U_{3,3} = 1$ se obtiene el método de Crout.



##### Factorización Doolitle

**Paso 1**: Haciendo $l_{1,1} = l_{2,2} = l_{3,3} = 1$

Del _Sistema 1_, se tiene

$$\begin{align*}
u_{1,1} &= a_{1,1}\\
u_{1,2} &= a_{1,2}\\
u_{1,3} &= a_{1,3}\\
\end{align*}$$

**Paso 2**: Sustituyendo los resultados del **Paso** anterior en el _Sistema 2_, se tiene

$$\begin{align*}
l_{2,1} &= \dfrac{a_{2,1}}{u_{1,1}} = \dfrac{a_{2,1}}{a_{1,1}}\\
u_{2,2} &= a_{2,2} - l_{2,1}u_{1,2} = a_{2,2}- \dfrac{a_{2,1}}{u_{1,1}}a_{1,2}\\
u_{2,3} &= a_{2,3} - l_{2,1}u_{1,3} = a_{2,3}- \dfrac{a_{2,1}}{u_{1,1}}a_{1,3}
\end{align*}$$

**Paso 3**: Sustituyendo los resultados de los **Pasos** anteriores en el _Sistema 3_, se tiene

$$\begin{align*}
l_{3,1} &= \dfrac{a_{3,1}}{u_{1,1}} = \dfrac{a_{3,1}}{a_{1,1}}\\
l_{3,2} &= \dfrac{a_{3,2}-l_{3,1}u_{1,2}}{u_{2,2}} =\dfrac{a_{3,2}-\dfrac{a_{3,1}}{a_{1,1}}a_{1,2}}{a_{2,2}-\dfrac{a_{2,1}}{a_{1,1}}a_{1,2}}\\
u_{3,3} &= a_{3,3}-l_{3,1}u_{1,3}-l_{3,2}u_{2,3} = a_{3,3}-\dfrac{a_{3,1}}{a_{1,1}}a_{1,3}-\left[\dfrac{a_{3,2}-\dfrac{a_{3,1}}{a_{1,1}}a_{1,2}}{a_{2,2}-\dfrac{a_{2,1}}{a_{1,1}}a_{1,2}} \right]\left[a_{2,3}- \dfrac{a_{2,1}}{u_{1,1}}a_{1,3} \right]
\end{align*}$$

Las ecuaciones anteriores conviene generalizarlas para poder programarlas.

$$\begin{align*}
u_{i,j} &= a_{i,j} - \sum_{k=1}^{i-1}l_{i,k}u_{k,j};j=i,i+1,\ldots,n\\
l_{i,j} &= \dfrac{1}{u_{j,j}}\left(a_{i,j}-\sum_{k=1}^{j-1}u_{k,j}l_{i,k}\right); i=j+1,\ldots,n\\
l_{i,i}&=1;i=1,2,\ldots,n
\end{align*}$$

**Ejemplo** Resuelva por el método de Doolitle el sistema 

$$\begin{matrix}
4\, x_1 & - & 9\,x_2 & + & 2\,x_3 & = & 5\\
2\, x_1 & - & 4\,x_2 & + & 6\,x_3 & = & 3\\
 \, x_1 & - &  \,x_2 & + & 3\,x_3 & = & 4\\
\end{matrix}$$

In [ ]:
from scipy.linalg import lu
A = np.array([[4,9,2],[2,-4,6],[1,-1,3]])
b = np.array([5,3,4])
p,l,u = lu(A)

$$\begin{align*}
A\boldsymbol{x}&=\boldsymbol{b}\\
PA\boldsymbol{x}&=P\boldsymbol{b}\\
PLU\boldsymbol{x}&=P\boldsymbol{b}
\end{align*}$$

In [ ]:
l

In [ ]:
u

In [ ]:
p

In [ ]:
np.allclose(A - p @ l @ u, np.zeros_like(A))

In [ ]:
p@b

In [ ]:
b@p

In [ ]:
c = np.linalg.solve(l,b)
c

In [ ]:
x = np.linalg.solve(u,c)
x

In [ ]:
np.allclose(np.dot(A,x),b)

**Ejemplo**: Resuelva

$$\begin{matrix}
10\, x_1 & + & \,x_2 & - & 5\,x_3 & = & 1\\
-20\, x_1 & + & 3\,x_2 & + & 20\,x_3 & = & 2\\
 5\, x_1 & + &  3\,x_2 & + & 5\,x_3 & = & 6\\
\end{matrix}$$

In [ ]:
A = np.array([[10,1,-5],[-20,3,20],[5,3,5]])
b = np.array([1,2,6])
p,l,u = lu(A)

In [ ]:
p

In [ ]:
l

In [ ]:
u

In [ ]:
np.allclose(A - p @ l @ u, np.zeros_like(A))

In [ ]:
p@b

In [ ]:
b@p

In [ ]:
c = np.linalg.solve(l,b@p)
c

In [ ]:
x = np.linalg.solve(u,c)

In [ ]:
x

Otro ejemplo

In [ ]:
from scipy.linalg import lu_factor, lu_solve
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
b = np.array([1, 1, 1, 1])
lu, piv = lu_factor(A)
x = lu_solve((lu, piv), b)
np.allclose(A @ x - b, np.zeros_like(b))

True

In [ ]:
lu

array([[ 7.        ,  5.        ,  6.        ,  6.        ],
       [ 0.28571429,  3.57142857,  6.28571429,  5.28571429],
       [ 0.71428571,  0.12      , -1.04      ,  3.08      ],
       [ 0.71428571, -0.44      , -0.46153846,  7.46153846]])

In [ ]:
piv


array([2, 2, 3, 3], dtype=int32)

In [ ]:
x

array([ 0.05154639, -0.08247423,  0.08247423,  0.09278351])