# Método de Newton

In [ ]:
# Funciones
def f1(x,y):
  return x**2 - 10*x + y**2 + 8.0

def f2(x,y):
  return x*y**2 + x -10*y + 8.0

In [ ]:
# Parciales de f1 y f2

def df1x(x,y):
  return 2*x - 10

def df1y(x,y):
  return 2*y

def df2x(x,y):
  return y**2 + 1

def df2y(x,y):
  return 2*x*y - 10

In [ ]:
import numpy as np


## Primera iteración

In [ ]:
# Valores iniciales
x0 = 0.0
y0 = 0.0

In [ ]:
A = np.array([[df1x(x0,y0), df1y(x0,y0)],[df2x(x0,y0),df2y(x0,y0)]])

In [ ]:
print(A)

[[-10.   0.]
 [  1. -10.]]


In [ ]:
b = np.array([[-f1(x0,y0)],[-f2(x0,y0)]])

In [ ]:
print(b)

[[-8.]
 [-8.]]


$$A\bar{x}=\bar{b}$$

$$\bar{x} = A^{-1}\bar{b}$$

In [ ]:
A_inversa = np.linalg.inv(A)

In [ ]:
print(A_inversa)

[[-0.1  -0.  ]
 [-0.01 -0.1 ]]


In [ ]:
x = A_inversa.dot(b)

In [ ]:
print(x)

[[0.8 ]
 [0.88]]


x = [[0,0],[1,0]]

In [ ]:
x[0,0]

0.8

In [ ]:
x[1,0]

0.8800000000000001

In [ ]:
x1 = x0 + x[0,0]
y1 = y0 + x[1,0]

In [ ]:
print(x1,y1)

0.8 0.8800000000000001


In [ ]:
d = ((x1-x0)**2 + (y1-y0)**2)**(1/2)

In [ ]:
print(d)

1.1892854997854805


In [ ]:
d <= 0.0001


False

**Tarea**: continuar con las iteraciones hasta que se cumpla que $d<=0.0001$.

## Código

In [ ]:
from IPython import get_ipython
get_ipython().magic('reset -sf')

In [ ]:
# Datos requeridos

x0, y0 = 0.0, 0.0    # Valores inicialles
EPSILON = 0.0001    # Criterio de paro para la distancia
MAXIT = 100    # Criterio por sino se cumple d <= EPSILON

# Funciones f1 y f2

def f1(x,y):
  return x**2 - 10*x + y**2 + 8.0

def f2(x,y):
  return x*y**2 + x -10*y + 8.0

# Parciales de f1 y f2

def df1x(x,y):
  return 2*x - 10

def df1y(x,y):
  return 2*y

def df2x(x,y):
  return y**2 + 1

def df2y(x,y):
  return 2*x*y - 10

# Bibliotecas

import numpy as np

for i in range(MAXIT):
  A = np.array([[df1x(x0,y0), df1y(x0,y0)],[df2x(x0,y0),df2y(x0,y0)]])
  b = np.array([[-f1(x0,y0)],[-f2(x0,y0)]])
  A_inversa = np.linalg.inv(A)
  x = A_inversa.dot(b)
  x1 = x0 + x[0,0]
  y1 = y0 + x[1,0]
  d = ((x1-x0)**2 + (y1-y0)**2)**(1/2)  
  if d <= EPSILON:
    print("--------------")
    print("Iteracion = ", i, "\nSolucion = ",x1,y1)
    break
  else:
    x0 = x1
    y0 = y1

--------------
Iteracion =  3 
Solucion =  0.9999999997010981 0.9999999996065294


## Uso del método *root* de la biblioteca scipy

Este método por default usa el método _hybr_. Sin embargo, existe la opción de seleccionar otros métodos:
+ root(method='hybr')
+ root(method='lm')
+ root(method='broyden1')
+ root(method='broyden2')
+ root(method='anderson')
+ root(method='linearmixing')
+ root(method='diagbroyden')
+ root(method='excitingmixing')
+ root(method='krylov')
+ root(method='df-sane')

Para mayor detalle sobre los métodos, se recomienda revisar la [documentación de la biblioteca optmize.](https://docs.scipy.org/doc/scipy/reference/optimize.html)

In [ ]:
from IPython import get_ipython
get_ipython().magic('reset -sf')

In [ ]:
from scipy.optimize import root
import numpy as np

"""
Recuerden que en este caso x = x[0] y y = x[1]
"""

def f(x):
  return [x[0]**2 - 10*x[0] + x[1]**2 + 8.0,
          x[0]*x[1]**2 + x[0] -10*x[1] + 8.0]

def jacobiano(x):
  return [[2*x[0] - 10, 2*x[1]], 
          [x[1]**2 + 1, 2*x[0]*x[1] - 10 ] ]


In [ ]:
sol = root(f, [0, 0], jac=jacobiano, method='hybr')

In [ ]:
sol.x

array([1., 1.])

### Llamando a las funciones y al jacobiano en la misma función.

In [ ]:
def fun(x):
  f = [x[0]**2 - 10*x[0] + x[1]**2 + 8.0,
          x[0]*x[1]**2 + x[0] -10*x[1] + 8.0]
  df = [[2*x[0] - 10, 2*x[1]], 
        [x[1]**2 + 1, 2*x[0]*x[1] - 10 ] ]
  
  return f, df

In [ ]:
sol = root(fun, [0, 0], jac=True, method='hybr')

In [ ]:
sol.x

array([1., 1.])